package com.dsa.dsa_requests;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class RequestData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "REQUESTDATA_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "REQUESTDATA_ID_SEQ", name = "REQUESTDATA_ID_GENERATOR")
	private java.lang.Long id;

	private java.lang.String description;

	private boolean approved;

	private java.lang.String location;

	private java.lang.String caseId;

	private java.lang.String opportunityId;

	private String startDateTime;

	private String endDateTime;

	private java.lang.String duration;

	public RequestData() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public boolean isApproved() {
		return this.approved;
	}

	public void setApproved(boolean approved) {
		this.approved = approved;
	}

	public java.lang.String getLocation() {
		return this.location;
	}

	public void setLocation(java.lang.String location) {
		this.location = location;
	}

	public java.lang.String getCaseId() {
		return this.caseId;
	}

	public void setCaseId(java.lang.String caseId) {
		this.caseId = caseId;
	}

	public java.lang.String getOpportunityId() {
		return this.opportunityId;
	}

	public void setOpportunityId(java.lang.String opportunityId) {
		this.opportunityId = opportunityId;
	}

	public java.lang.String getDuration() {
		return this.duration;
	}

	public void setDuration(java.lang.String duration) {
		this.duration = duration;
	}

	public java.lang.String getStartDateTime() {
		return this.startDateTime;
	}

	public void setStartDateTime(java.lang.String startDateTime) {
		this.startDateTime = startDateTime;
	}

	public java.lang.String getEndDateTime() {
		return this.endDateTime;
	}

	public void setEndDateTime(java.lang.String endDateTime) {
		this.endDateTime = endDateTime;
	}

	public RequestData(java.lang.Long id, java.lang.String description,
			boolean approved, java.lang.String location,
			java.lang.String caseId, java.lang.String opportunityId,
			java.lang.String startDateTime, java.lang.String endDateTime,
			java.lang.String duration) {
		this.id = id;
		this.description = description;
		this.approved = approved;
		this.location = location;
		this.caseId = caseId;
		this.opportunityId = opportunityId;
		this.startDateTime = startDateTime;
		this.endDateTime = endDateTime;
		this.duration = duration;
	}

}